# Pytorch_basics

Adapted from  Kaggle practice notebooks<Add the link here>

In [1]:
# Essential imports
import torch
import numpy as np

In [2]:
# numpy array
array = [[1,2,3],[4,5,6]]
first_array = np.array(array) # 2x3 array
print("Array Type: {}".format(type(first_array))) # type
print("Array Shape: {}".format(np.shape(first_array))) # shape
print(first_array)

Array Type: <class 'numpy.ndarray'>
Array Shape: (2, 3)
[[1 2 3]
 [4 5 6]]


In [3]:
# pytorch array
tensor = torch.Tensor(array)
print("Array Type: {}".format(tensor.type)) # type
print("Array Shape: {}".format(tensor.shape)) # shape
print(tensor)

Array Type: <built-in method type of Tensor object at 0x000001FD4175EAB0>
Array Shape: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
# numpy ones
print("Numpy {}\n".format(np.ones((2,3))))

# pytorch ones
print(torch.ones((2,3)))

Numpy [[1. 1. 1.]
 [1. 1. 1.]]

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# numpy random
print("Numpy {}\n".format(np.random.rand(2,3)))

# pytorch random
print(torch.rand(2,3))

Numpy [[0.84528734 0.50226413 0.72462462]
 [0.03371716 0.77745834 0.24055968]]

tensor([[0.6120, 0.7894, 0.6446],
        [0.7442, 0.7028, 0.5795]])


In [6]:
# random numpy array
array = np.random.rand(2,2)
print("{} {}\n".format(type(array),array))

# from numpy to tensor
from_numpy_to_tensor = torch.from_numpy(array)
print("{}\n".format(from_numpy_to_tensor))

# from tensor to numpy
tensor = from_numpy_to_tensor
from_tensor_to_numpy = tensor.numpy()
print("{} {}\n".format(type(from_tensor_to_numpy),from_tensor_to_numpy))

<class 'numpy.ndarray'> [[0.04345701 0.01102962]
 [0.69061835 0.65837278]]

tensor([[0.0435, 0.0110],
        [0.6906, 0.6584]], dtype=torch.float64)

<class 'numpy.ndarray'> [[0.04345701 0.01102962]
 [0.69061835 0.65837278]]




Basic Math with Pytorch

    Resize: view()
    a and b are tensor.
    Addition: torch.add(a,b) = a + b
    Subtraction: a.sub(b) = a - b
    Element wise multiplication: torch.mul(a,b) = a * b
    Element wise division: torch.div(a,b) = a / b
    Mean: a.mean()
    Standart Deviation (std): a.std()



In [7]:
# create tensor 
tensor = torch.ones(3,3)
print("\n",tensor)

# Resize
print("{}{}\n".format(tensor.view(9).shape,tensor.view(9)))

# Addition
print("Addition: {}\n".format(torch.add(tensor,tensor)))

# Subtraction
print("Subtraction: {}\n".format(tensor.sub(tensor)))

# Element wise multiplication
print("Element wise multiplication: {}\n".format(torch.mul(tensor,tensor)))

# Element wise division
print("Element wise division: {}\n".format(torch.div(tensor,tensor)))

# Mean
tensor = torch.Tensor([1,2,3,4,5])
print("Mean: {}".format(tensor.mean()))

# Standart deviation (std)
print("std: {}".format(tensor.std()))


 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([9])tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

Addition: tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

Subtraction: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Element wise multiplication: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Element wise division: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Mean: 3.0
std: 1.5811388492584229


### Take down below content to different notebook as practice items

In [2]:
# torch.tensor
t1 = torch.tensor([1., 2., 3., 4., 5.], dtype=torch.float64)
t2 = torch.tensor([5., 6., 7., 8., 9.], dtype=torch.float16)

print ('t1: ', t1)
print ('t2: ', t2)

t1:  tensor([1., 2., 3., 4., 5.], dtype=torch.float64)
t2:  tensor([5., 6., 7., 8., 9.], dtype=torch.float16)


In [3]:
# torch.is_tensor 
t1 = torch.tensor([1, 2, 3, 4, 5])
t2 = [1, 2, 3, 4, 5]

print (torch.is_tensor(t1))
print (torch.is_tensor(t2))

True
False


In [4]:
# torch,is_storage
s1 = torch.FloatStorage(128)
s2 = np.float(128)

print (torch.is_storage(s1))
print (torch.is_storage(s2))

True
False


In [5]:
# torch.set_default_type
# Sets the default torch.tensor() type to a floating point tensor type

t1 = torch.tensor([1., 2., 3])

print ('The default type is: ', t1.dtype)

torch.set_default_dtype(torch.float64)

t2 = torch.tensor([1., 2., 3])

print ('Now the default dtype is: ', t2.dtype)

The default type is:  torch.float32
Now the default dtype is:  torch.float64


In [6]:
# torch.get_default_dtype
# Returns the current default floating point

print ('The default dtype is: ', torch.get_default_dtype())

torch.set_default_dtype(torch.float16)
print ('The default dtype now is: ', torch.get_default_dtype())

torch.set_default_dtype(torch.float64)
print ('The default dtype now is: ', torch.get_default_dtype())

# Cannot set the default type to non-float type
#torch.set_default_dtype(torch.int16)
#print ('The default dtype now is: ', torch.get_default_dtype())

The default dtype is:  torch.float64
The default dtype now is:  torch.float16
The default dtype now is:  torch.float64


In [7]:
# torch.set_default_tensor_type
# Sets the default torch.tensor() type to a floating point tensor type

print ('The default dtype is: ', torch.get_default_dtype())

torch.set_default_tensor_type(torch.FloatTensor)
print ('The default dtype now is: ', torch.get_default_dtype())

torch.set_default_tensor_type(torch.DoubleTensor)
print ('The default dtype now is: ', torch.get_default_dtype())

The default dtype is:  torch.float64
The default dtype now is:  torch.float32
The default dtype now is:  torch.float64


In [8]:
# torch.numel
# Returns the total number of elements in the tensor

t1 = torch.randn(4, 5)
print ('The number of elements in t1: ', t1.numel())

t2 = torch.randn(5, 4, 2)
print ('The number of elements in t2: ', t2.numel())

The number of elements in t1:  20
The number of elements in t2:  40


In [ ]:
# torch.set_printoptions
# Helps set the options for printing

In [9]:
# torch.set_flush_denormal
# Disables denormal floating numbers on CPU

torch.set_flush_denormal(True)
t1 = torch.tensor([1e-323, 1e-235, 1e-121], dtype=torch.float64)
print ('t1: ', t1)

torch.set_flush_denormal(False)
t2 = torch.tensor([1e-323, 1e-235, 1e-121], dtype=torch.float64)
print ('t2: ', t2)

t1:  tensor([0.0000, 0.0000, 0.0000])
t2:  tensor([9.8813e-324, 1.0000e-235, 1.0000e-121])
